from __future__ import annotations

from typing import Dict, List, TypedDict

from app.modules.reports.plan_config import (
    BASIC_SECTIONS,
    ENTERPRISE_SECTIONS,
    STANDARD_SECTIONS,
)

class HeadingPair(TypedDict):
    en: str
    hi: str


SECTION_HEADING_MAP: Dict[str, HeadingPair] = {
    "plan_overview": {"en": "Plan Overview", "hi": "योजना अवलोकन"},
    "basic_details": {"en": "Basic Details", "hi": "मूल विवरण"},
    "mulank_analysis": {"en": "Mulank Analysis", "hi": "मूलांक विश्लेषण"},
    "bhagyank_analysis": {"en": "Bhagyank Analysis", "hi": "भाग्यांक विश्लेषण"},
    "mobile_number_total": {"en": "Mobile Number Total", "hi": "मोबाइल नंबर कुल योग"},
    "mobile_digit_analysis": {"en": "Mobile Digit Analysis", "hi": "मोबाइल अंकों का विश्लेषण"},
    "mobile_energy_description": {"en": "Mobile Energy Description", "hi": "मोबाइल ऊर्जा विवरण"},
    "mulank_connection": {"en": "Mulank Connection", "hi": "मूलांक कनेक्शन"},
    "bhagyank_connection": {"en": "Bhagyank Connection", "hi": "भाग्यांक कनेक्शन"},
    "combo_analysis": {"en": "Combo Analysis", "hi": "संयुक्त विश्लेषण"},
    "lucky_numbers": {"en": "Lucky Numbers", "hi": "शुभ अंक"},
    "unlucky_numbers": {"en": "Unlucky Numbers", "hi": "अशुभ अंक"},
    "neutral_numbers": {"en": "Neutral Numbers", "hi": "तटस्थ अंक"},
    "lucky_numbers_unlucky_numbers_neutral_numbers": {
        "en": "Lucky, Unlucky and Neutral Numbers",
        "hi": "शुभ, अशुभ और तटस्थ अंक",
    },
    "color_recommendation": {"en": "Color Recommendation", "hi": "रंग सुझाव"},
    "health_insight": {"en": "Health Insight", "hi": "स्वास्थ्य अंतर्दृष्टि"},
    "wealth_insight": {"en": "Wealth Insight", "hi": "धन अंतर्दृष्टि"},
    "relationship_insight": {"en": "Relationship Insight", "hi": "संबंध अंतर्दृष्टि"},
    "health_wealth_relationship_insight": {
        "en": "Health, Wealth and Relationship Insight",
        "hi": "स्वास्थ्य, धन और संबंध संकेत",
    },
    "remedies": {"en": "Remedies", "hi": "उपाय"},
    "remedies_logic": {"en": "Remedies Logic", "hi": "उपाय तर्क"},
    "lucky_number_usage": {"en": "Lucky Number Usage", "hi": "शुभ अंक उपयोग"},
    "mobile_recommendation": {"en": "Mobile Recommendation", "hi": "मोबाइल अनुशंसा"},
    "mobile_cover_color": {"en": "Mobile Cover Color", "hi": "मोबाइल कवर रंग"},
    "mantra_recommendation": {"en": "Mantra Recommendation", "hi": "मंत्र अनुशंसा"},
    "final_outcome": {"en": "Final Outcome", "hi": "अंतिम परिणाम"},
    "name_analysis_type": {"en": "Name Analysis Type", "hi": "नाम विश्लेषण प्रकार"},
    "name_correction": {"en": "Name Correction", "hi": "नाम सुधार"},
    "prefix_suffix_suggestion": {"en": "Prefix / Suffix Suggestion", "hi": "प्रिफिक्स/सुफिक्स सुझाव"},
    "name_correction_basis": {"en": "Name Correction Basis", "hi": "नाम सुधार आधार"},
    "wallpaper_suggestion": {"en": "Wallpaper Suggestion", "hi": "वॉलपेपर सुझाव"},
    "charging_direction": {"en": "Charging Direction", "hi": "चार्जिंग दिशा"},
    "bracelet_crystal_suggestion": {"en": "Bracelet / Crystal Suggestion", "hi": "कंगन/क्रिस्टल सुझाव"},
    "gemstone_recommendation": {"en": "Gemstone Recommendation", "hi": "रत्न अनुशंसा"},
    "astrology_integration": {"en": "Astrology Integration", "hi": "ज्योतिष एकीकरण"},
    "vedic_logic_integration": {"en": "Vedic Logic Integration", "hi": "वैदिक तर्क एकीकरण"},
    "planetary_support_mapping": {"en": "Planetary Support Mapping", "hi": "ग्रह समर्थन मैपिंग"},
    "signature_analysis": {"en": "Signature Analysis", "hi": "हस्ताक्षर विश्लेषण"},
    "space_direction_guidance": {"en": "Space / Direction Guidance", "hi": "स्थान/दिशा मार्गदर्शन"},
    "ongoing_guidance": {"en": "Ongoing Guidance", "hi": "निरंतर मार्गदर्शन"},
    "profile_snapshot": {"en": "Profile Snapshot", "hi": "प्रोफाइल स्नैपशॉट"},
    "dashboard": {"en": "Deterministic Dashboard", "hi": "नियतात्मक डैशबोर्ड"},
    "executive_summary": {"en": "Executive Numerology Summary", "hi": "कार्यकारी अंक विश्लेषण सार"},
    "number_interaction": {"en": "Number Interaction", "hi": "अंकों का परस्पर प्रभाव"},
    "name_numerology": {"en": "Name Numerology", "hi": "नाम अंक विश्लेषण"},
    "name_analysis": {"en": "Name Analysis", "hi": "नाम विश्लेषण"},
    "name_number_total": {"en": "Name Number Total", "hi": "नाम नंबर कुल योग"},
    "name_correction_options": {"en": "Name Correction Options", "hi": "नाम सुधार विकल्प"},
    "prefix_suffix_suggestions": {"en": "Prefix / Suffix Suggestions", "hi": "प्रिफिक्स / सुफिक्स सुझाव"},
    "name_correction_logic_explanation": {"en": "Name Correction Logic", "hi": "नाम सुधार तर्क"},
    "email_numerology": {"en": "Email Numerology", "hi": "ईमेल अंक विश्लेषण"},
    "personality_profile": {"en": "Personality Profile", "hi": "व्यक्तित्व प्रोफाइल"},
    "focus_snapshot": {"en": "Focus Snapshot", "hi": "फोकस स्नैपशॉट"},
    "personal_year_direction": {"en": "Personal Year Direction", "hi": "व्यक्तिगत वर्ष दिशा"},
    "lucky_dates": {"en": "Lucky Dates", "hi": "शुभ तिथियां"},
    "color_alignment": {"en": "Color Alignment", "hi": "रंग संतुलन"},
    "remedy_suggestions": {"en": "Remedy Suggestions", "hi": "उपाय सुझाव"},
    "closing_summary": {"en": "Closing Summary", "hi": "समापन सार"},
    "lo_shu_grid": {"en": "Lo Shu Grid", "hi": "लो शू ग्रिड"},
    "missing_numbers": {"en": "Missing Numbers", "hi": "अनुपस्थित अंक संकेत"},
    "repeating_numbers": {"en": "Repeating Numbers", "hi": "दोहराए गए अंक संकेत"},
    "mobile_numerology": {"en": "Mobile Numerology", "hi": "मोबाइल अंक विश्लेषण"},
    "mobile_life_compatibility": {"en": "Mobile-Life Compatibility", "hi": "मोबाइल-जीवन संगतता"},
    "mobile_name_combo_recommendation": {"en": "Mobile + Name Combo", "hi": "मोबाइल-नाम संयोजन सुझाव"},
    "summary_and_priority_actions": {"en": "Summary and Priority Actions", "hi": "सारांश और प्राथमिक कार्य"},
    "business_numerology": {"en": "Business Numerology", "hi": "व्यवसाय अंक विश्लेषण"},
    "digital_numerology": {"en": "Digital Numerology", "hi": "डिजिटल अंक विश्लेषण"},
    "career_financial": {"en": "Career and Financial Analysis", "hi": "करियर और वित्तीय विश्लेषण"},
    "relationship_patterns": {"en": "Relationship Patterns", "hi": "संबंध पैटर्न"},
    "health_tendencies": {"en": "Health Tendencies", "hi": "स्वास्थ्य प्रवृत्तियां"},
    "decision_style": {"en": "Decision Style", "hi": "निर्णय शैली"},
    "growth_blockers": {"en": "Growth Blockers", "hi": "विकास अवरोधक"},
    "action_plan_90_days": {"en": "90-Day Action Plan", "hi": "90-दिवसीय कार्य योजना"},
    "life_timeline": {"en": "Life Timeline", "hi": "जीवन समयरेखा"},
    "strategic_life_theme": {"en": "Strategic Life Theme", "hi": "रणनीतिक जीवन थीम"},
    "leadership_archetype": {"en": "Leadership Archetype", "hi": "नेतृत्व प्रतिरूप"},
    "wealth_strategy": {"en": "Wealth Strategy", "hi": "समृद्धि रणनीति"},
    "opportunity_windows": {"en": "Opportunity Windows", "hi": "अवसर समय-खिड़कियां"},
    "decision_timing": {"en": "Decision Timing", "hi": "निर्णय समय निर्धारण"},
    "roadmap_12_months": {"en": "12-Month Roadmap", "hi": "12-महीने का रोडमैप"},
    "outlook_3_years": {"en": "3-Year Outlook", "hi": "3-वर्षीय दृष्टिकोण"},
    "life_alignment_scorecard": {"en": "Life Alignment Scorecard", "hi": "जीवन संतुलन स्कोरकार्ड"},
    "strategic_correction": {"en": "Strategic Correction", "hi": "रणनीतिक सुधार"},
    "growth_blueprint": {"en": "Growth Blueprint", "hi": "विकास ब्लूप्रिंट"},

    "mobile_digit_pattern": {"en": "Mobile Digit Pattern", "hi": "मोबाइल अंक पैटर्न"},
    "life_area_impact": {"en": "Life Area Impact", "hi": "जीवन क्षेत्र प्रभाव"},
    "name_vibration_optimization": {"en": "Name Vibration Optimization", "hi": "नाम कंपन अनुकूलन"},
    "name_mobile_combo": {"en": "Name + Mobile Combo", "hi": "नाम + मोबाइल संयोजन"},
    "numerology_architecture": {"en": "Numerology Architecture", "hi": "अंक वास्तुकला"},
    "planetary_influence": {"en": "Planetary Influence", "hi": "ग्रह प्रभाव"},
    "vedic_remedy": {"en": "Vedic Remedy Protocol", "hi": "वैदिक उपाय"},
    "karmic_pattern_intelligence": {"en": "Karmic Pattern Insight", "hi": "कर्मिक पैटर्न बुद्धि"},
    "pinnacle_challenge_cycle_intelligence": {"en": "Pinnacle & Challenge Cycles", "hi": "पिनैकल व चैलेंज चक्र"},
    "signature_intelligence": {"en": "Signature Analysis", "hi": "हस्ताक्षर बुद्धि"},
    "business_name_intelligence": {"en": "Business / Brand Naming", "hi": "व्यवसाय / ब्रांड नाम"},
    "environment_alignment": {"en": "Space & Direction Guidance", "hi": "स्थान / दिशा संरेखण"},
    "strategic_execution_roadmap": {"en": "Strategic Execution Roadmap", "hi": "रणनीतिक निष्पादन रोडमैप"},
    "full_identity_profile": {"en": "Full Identity Profile", "hi": "पूर्ण पहचान प्रोफ़ाइल"},
    "core_numbers": {"en": "Core Numbers", "hi": "मुख्य अंक"},
    "advanced_name_numerology": {"en": "Advanced Name Numerology", "hi": "उन्नत नाम अंक विश्लेषण"},
    "karmic_name_analysis": {"en": "Karmic Name Analysis", "hi": "कर्मिक नाम विश्लेषण"},
    "planetary_name_support_mapping": {"en": "Planetary Name Support Mapping", "hi": "ग्रह-आधारित नाम समर्थन मैपिंग"},
    "multi_name_correction_options": {"en": "Multi Name Correction Options", "hi": "बहु-नाम सुधार विकल्प"},
    "name_optimization_scoring": {"en": "Name Optimization Scoring", "hi": "नाम अनुकूलन स्कोर"},
    "prefix_suffix_advanced_logic": {"en": "Prefix Suffix Advanced Logic", "hi": "उन्नत प्रिफिक्स / सुफिक्स तर्क"},
    "mobile_numerology_advanced": {"en": "Mobile Numerology Advanced", "hi": "उन्नत मोबाइल अंक विश्लेषण"},
    "mobile_digit_micro_analysis": {"en": "Mobile Digit Micro Analysis", "hi": "मोबाइल अंकों का सूक्ष्म विश्लेषण"},
    "mobile_energy_forecasting": {"en": "Mobile Energy Forecasting", "hi": "मोबाइल ऊर्जा पूर्वानुमान"},
    "name_mobile_alignment": {"en": "Name Mobile Alignment", "hi": "नाम और मोबाइल सामंजस्य"},
    "dob_name_alignment": {"en": "Dob Name Alignment", "hi": "जन्मतिथि और नाम सामंजस्य"},
    "dob_mobile_alignment": {"en": "Dob Mobile Alignment", "hi": "जन्मतिथि और मोबाइल सामंजस्य"},
    "full_system_alignment_score": {"en": "Full System Alignment Score", "hi": "पूर्ण सिस्टम एलाइनमेंट स्कोर"},
    "strength_vs_risk_matrix": {"en": "Strength Vs Risk Matrix", "hi": "ताकत बनाम जोखिम मैट्रिक्स"},
    "life_area_scores": {"en": "Life Area Scores", "hi": "जीवन-क्षेत्र स्कोर"},
    "mulank_deep_analysis": {"en": "Mulank Deep Analysis", "hi": "मूलांक गहन विश्लेषण"},
    "bhagyank_destiny_roadmap": {"en": "Bhagyank Destiny Roadmap", "hi": "भाग्यांक डेस्टिनी रोडमैप"},
    "lo_shu_grid_advanced": {"en": "Lo Shu Grid Advanced", "hi": "उन्नत लो-शू ग्रिड"},
    "planetary_influence_mapping": {"en": "Planetary Influence Mapping", "hi": "ग्रह प्रभाव मैपिंग"},
    "current_planetary_phase": {"en": "Current Planetary Phase", "hi": "वर्तमान ग्रह चरण"},
    "upcoming_transit_highlights": {"en": "Upcoming Transit Highlights", "hi": "आगामी गोचर संकेत"},
    "personal_year_analysis": {"en": "Personal Year Analysis", "hi": "व्यक्तिगत वर्ष विश्लेषण"},
    "monthly_cycle_analysis": {"en": "Monthly Cycle Analysis", "hi": "मासिक चक्र विश्लेषण"},
    "critical_decision_windows": {"en": "Critical Decision Windows", "hi": "महत्वपूर्ण निर्णय समय-खिड़कियाँ"},
    "wealth_cycle_analysis": {"en": "Wealth Cycle Analysis", "hi": "धन चक्र विश्लेषण"},
    "career_growth_timeline": {"en": "Career Growth Timeline", "hi": "करियर विकास टाइमलाइन"},
    "relationship_timing_patterns": {"en": "Relationship Timing Patterns", "hi": "संबंध समय-पैटर्न"},
    "dynamic_lucky_numbers": {"en": "Dynamic Lucky Numbers", "hi": "गतिशील शुभ अंक"},
    "situational_caution_numbers": {"en": "Situational Caution Numbers", "hi": "परिस्थितिजन्य सावधानी अंक"},
    "neutral_number_strategy_usage": {"en": "Neutral Number Strategy Usage", "hi": "तटस्थ अंक उपयोग रणनीति"},
    "color_strategy": {"en": "Color Strategy", "hi": "रंग रणनीति"},
    "energy_objects_recommendation": {"en": "Energy Objects Recommendation", "hi": "ऊर्जा वस्तु सुझाव"},
    "advanced_remedies_engine": {"en": "Advanced Remedies Engine", "hi": "उन्नत उपाय इंजन"},
    "business_brand_naming": {"en": "Business Brand Naming", "hi": "व्यवसाय / ब्रांड नाम सुझाव"},
    "signature_energy_analysis": {"en": "Signature Energy Analysis", "hi": "हस्ताक्षर ऊर्जा विश्लेषण"},
    "mobile_optimization_strategy": {"en": "Mobile Optimization Strategy", "hi": "मोबाइल अनुकूलन रणनीति"},
    "life_strategy_recommendations": {"en": "Life Strategy Recommendations", "hi": "जीवन रणनीति सुझाव"},
    "priority_action_plan": {"en": "Priority Action Plan", "hi": "प्राथमिक कार्य योजना"},
    "risk_alerts_and_mitigation": {"en": "Risk Alerts And Mitigation", "hi": "जोखिम चेतावनी और निवारण"},
    "premium_summary_narrative": {"en": "Premium Summary Narrative", "hi": "प्रीमियम समापन सार"},
}

SECTION_HEADING_MAP.update(
    {
        "plan_overview": {"en": "Plan Overview", "hi": "योजना अवलोकन"},
        "required_inputs": {"en": "Required Inputs", "hi": "आवश्यक इनपुट"},
        "core_purpose": {"en": "Core Purpose", "hi": "मुख्य उद्देश्य"},
        "primary_focus": {"en": "Primary Focus", "hi": "मुख्य फोकस"},
        "deterministic_engine": {"en": "Deterministic Engine", "hi": "निर्धारित इंजन"},
        "ai_generation_layer": {"en": "AI Generation Layer", "hi": "AI निर्माण परत"},
        "recommendation_logic": {"en": "Recommendation Logic", "hi": "सिफारिश तर्क"},
        "narration_style": {"en": "Narration Style", "hi": "वर्णन शैली"},
        "ai_narration_role": {"en": "AI Narration Role", "hi": "AI वर्णन भूमिका"},
        "deterministic_role": {"en": "Deterministic Role", "hi": "निर्धारित भूमिका"},
        "ai_should_not_do": {"en": "What AI Should Not Do", "hi": "AI क्या न करे"},
        "ai_should_do": {"en": "What AI Should Do", "hi": "AI क्या करे"},
        "basic_details": {"en": "Basic Details", "hi": "मूल विवरण"},
        "mulank_analysis": {"en": "Mulank Analysis", "hi": "मूलांक विश्लेषण"},
        "bhagyank_analysis": {"en": "Bhagyank Analysis", "hi": "भाग्यांक विश्लेषण"},
        "mobile_numerology": {"en": "Mobile Numerology", "hi": "मोबाइल अंक विश्लेषण"},
        "mobile_number_total": {"en": "Mobile Number Total", "hi": "मोबाइल नंबर कुल योग"},
        "mobile_digit_analysis": {"en": "Mobile Digit Analysis", "hi": "मोबाइल अंकों का विश्लेषण"},
        "mobile_energy_description": {"en": "Mobile Energy Description", "hi": "मोबाइल ऊर्जा विवरण"},
        "mulank_connection": {"en": "Mulank Connection", "hi": "मूलांक कनेक्शन"},
        "bhagyank_connection": {"en": "Bhagyank Connection", "hi": "भाग्यांक कनेक्शन"},
        "combo_analysis": {"en": "Combo Analysis", "hi": "संयुक्त विश्लेषण"},
        "lo_shu_grid": {"en": "Lo Shu Grid", "hi": "लो-शू ग्रिड"},
        "lucky_numbers": {"en": "Lucky Numbers", "hi": "शुभ अंक"},
        "unlucky_numbers": {"en": "Unlucky Numbers", "hi": "अशुभ अंक"},
        "neutral_numbers": {"en": "Neutral Numbers", "hi": "तटस्थ अंक"},
        "lucky_numbers_unlucky_numbers_neutral_numbers": {
            "en": "Lucky, Unlucky and Neutral Numbers",
            "hi": "शुभ, अशुभ और तटस्थ अंक",
        },
        "color_recommendation": {"en": "Color Recommendation", "hi": "रंग सुझाव"},
        "health_insight": {"en": "Health Insight", "hi": "स्वास्थ्य अंतर्दृष्टि"},
        "wealth_insight": {"en": "Wealth Insight", "hi": "धन अंतर्दृष्टि"},
        "relationship_insight": {"en": "Relationship Insight", "hi": "संबंध अंतर्दृष्टि"},
        "health_wealth_relationship_insight": {
            "en": "Health, Wealth and Relationship Insight",
            "hi": "स्वास्थ्य, धन और संबंध संकेत",
        },
        "remedies": {"en": "Remedies", "hi": "उपाय"},
        "remedies_logic": {"en": "Remedies Logic", "hi": "उपाय तर्क"},
        "lucky_number_usage": {"en": "Lucky Number Usage", "hi": "शुभ अंक उपयोग"},
        "mobile_recommendation": {"en": "Mobile Recommendation", "hi": "मोबाइल अनुशंसा"},
        "mobile_cover_color": {"en": "Mobile Cover Color", "hi": "मोबाइल कवर रंग"},
        "mantra_recommendation": {"en": "Mantra Recommendation", "hi": "मंत्र अनुशंसा"},
        "final_outcome": {"en": "Final Outcome", "hi": "अंतिम परिणाम"},
        "name_numerology": {"en": "Name Numerology", "hi": "नाम अंक विश्लेषण"},
        "name_analysis_type": {"en": "Name Analysis Type", "hi": "नाम विश्लेषण प्रकार"},
        "name_correction": {"en": "Name Correction", "hi": "नाम सुधार"},
        "prefix_suffix_suggestion": {"en": "Prefix / Suffix Suggestion", "hi": "प्रिफिक्स/सुफिक्स सुझाव"},
        "name_correction_basis": {"en": "Name Correction Basis", "hi": "नाम सुधार आधार"},
        "name_mobile_combo": {"en": "Name + Mobile Combo", "hi": "नाम + मोबाइल संयोजन"},
        "wallpaper_suggestion": {"en": "Wallpaper Suggestion", "hi": "वॉलपेपर सुझाव"},
        "charging_direction": {"en": "Charging Direction", "hi": "चार्जिंग दिशा"},
        "bracelet_crystal_suggestion": {"en": "Bracelet / Crystal Suggestion", "hi": "कंगन/क्रिस्टल सुझाव"},
        "gemstone_recommendation": {"en": "Gemstone Recommendation", "hi": "रत्न अनुशंसा"},
        "personal_year": {"en": "Personal Year", "hi": "व्यक्तिगत वर्ष दिशा"},
        "decision_timing": {"en": "Decision Timing", "hi": "निर्णय समय"},
        "astrology_integration": {"en": "Astrology Integration", "hi": "ज्योतिष एकीकरण"},
        "vedic_logic_integration": {"en": "Vedic Logic Integration", "hi": "वैदिक तर्क एकीकरण"},
        "planetary_support_mapping": {"en": "Planetary Support Mapping", "hi": "ग्रह समर्थन मैपिंग"},
        "signature_analysis": {"en": "Signature Analysis", "hi": "हस्ताक्षर विश्लेषण"},
        "space_direction_guidance": {"en": "Space / Direction Guidance", "hi": "स्थान/दिशा मार्गदर्शन"},
        "ongoing_guidance": {"en": "Ongoing Guidance", "hi": "निरंतर मार्गदर्शन"},
        "mobile_digit_pattern": {"en": "Mobile Digit Pattern", "hi": "मोबाइल अंक पैटर्न"},
        "life_area_impact": {"en": "Life Area Impact", "hi": "जीवन क्षेत्र प्रभाव"},
        "name_vibration_optimization": {"en": "Name Vibration Optimization", "hi": "नाम कंपन अनुकूलन"},
        "numerology_architecture": {"en": "Numerology Architecture", "hi": "अंक वास्तुकला"},
        "planetary_influence": {"en": "Planetary Influence", "hi": "ग्रह प्रभाव"},
        "vedic_remedy": {"en": "Vedic Remedy Protocol", "hi": "वैदिक उपाय"},
        "karmic_pattern_intelligence": {"en": "Karmic Pattern Insight", "hi": "कर्मिक पैटर्न बुद्धि"},
        "pinnacle_challenge_cycle_intelligence": {"en": "Pinnacle & Challenge Cycles", "hi": "पिनैकल व चैलेंज चक्र"},
        "signature_intelligence": {"en": "Signature Analysis", "hi": "हस्ताक्षर बुद्धि"},
        "business_name_intelligence": {"en": "Business / Brand Naming", "hi": "व्यवसाय / ब्रांड नाम"},
        "environment_alignment": {"en": "Space & Direction Guidance", "hi": "स्थान / दिशा संरेखण"},
        "strategic_execution_roadmap": {"en": "Strategic Execution Roadmap", "hi": "रणनीतिक निष्पादन रोडमैप"},
    }
)
SECTION_KEY_TO_HEADING_KEY = {
    "plan_overview": "plan_overview",
    "basic_details": "basic_details",
    "mulank_analysis": "mulank_analysis",
    "bhagyank_analysis": "bhagyank_analysis",
    "mobile_number_total": "mobile_number_total",
    "mobile_digit_analysis": "mobile_digit_analysis",
    "mobile_energy_description": "mobile_energy_description",
    "mulank_connection": "mulank_connection",
    "bhagyank_connection": "bhagyank_connection",
    "combo_analysis": "combo_analysis",
    "lucky_numbers_unlucky_numbers_neutral_numbers": "lucky_numbers_unlucky_numbers_neutral_numbers",
    "lucky_numbers": "lucky_numbers",
    "unlucky_numbers": "unlucky_numbers",
    "neutral_numbers": "neutral_numbers",
    "color_recommendation": "color_recommendation",
    "health_wealth_relationship_insight": "health_wealth_relationship_insight",
    "health_insight": "health_insight",
    "wealth_insight": "wealth_insight",
    "relationship_insight": "relationship_insight",
    "remedies": "remedies",
    "remedies_logic": "remedies_logic",
    "lucky_number_usage": "lucky_number_usage",
    "mobile_recommendation": "mobile_recommendation",
    "mobile_cover_color": "mobile_cover_color",
    "mantra_recommendation": "mantra_recommendation",
    "final_outcome": "final_outcome",
    "name_analysis_type": "name_analysis_type",
    "name_correction": "name_correction",
    "prefix_suffix_suggestion": "prefix_suffix_suggestion",
    "name_correction_basis": "name_correction_basis",
    "name_analysis": "name_analysis",
    "name_number_total": "name_number_total",
    "name_correction_options": "name_correction_options",
    "prefix_suffix_suggestions": "prefix_suffix_suggestions",
    "name_correction_logic_explanation": "name_correction_logic_explanation",
    "mobile_name_combo_recommendation": "mobile_name_combo_recommendation",
    "summary_and_priority_actions": "summary_and_priority_actions",
    "wallpaper_suggestion": "wallpaper_suggestion",
    "charging_direction": "charging_direction",
    "bracelet_crystal_suggestion": "bracelet_crystal_suggestion",
    "gemstone_recommendation": "gemstone_recommendation",
    "astrology_integration": "astrology_integration",
    "vedic_logic_integration": "vedic_logic_integration",
    "planetary_support_mapping": "planetary_support_mapping",
    "signature_analysis": "signature_analysis",
    "space_direction_guidance": "space_direction_guidance",
    "ongoing_guidance": "ongoing_guidance",
    "profile": "profile_snapshot",
    "profile_overview": "profile_snapshot",
    "dashboard": "dashboard",
    "energy_dashboard": "dashboard",
    "executive_summary": "executive_summary",
    "number_interaction": "number_interaction",
    "name_numerology": "name_numerology",
    "email_numerology": "email_numerology",
    "email_identity_intelligence": "email_numerology",
    "personality_profile": "personality_profile",
    "focus_snapshot": "focus_snapshot",
    "personal_year": "personal_year_direction",
    "personal_year_direction": "personal_year_direction",
    "lucky_dates": "lucky_dates",
    "color_alignment": "color_alignment",
    "remedy": "remedy_suggestions",
    "remedy_suggestions": "remedy_suggestions",
    "closing_summary": "closing_summary",
    "lo_shu_grid": "lo_shu_grid",
    "missing_numbers": "missing_numbers",
    "repeating_numbers": "repeating_numbers",
    "mobile_numerology": "mobile_numerology",
    "mobile_number_numerology": "mobile_numerology",
    "mobile_number_intelligence": "mobile_numerology",
    "mobile_life_compatibility": "mobile_life_compatibility",
    "business_numerology": "business_numerology",
    "digital_numerology": "digital_numerology",
    "digital_discipline": "digital_numerology",
    "career_financial": "career_financial",
    "relationship_patterns": "relationship_patterns",
    "health_tendencies": "health_tendencies",
    "decision_style": "decision_style",
    "growth_blockers": "growth_blockers",
    "action_plan_90_days": "action_plan_90_days",
    "life_timeline": "life_timeline",
    "strategic_life_theme": "strategic_life_theme",
    "leadership_archetype": "leadership_archetype",
    "wealth_strategy": "wealth_strategy",
    "opportunity_windows": "opportunity_windows",
    "decision_timing": "decision_timing",
    "roadmap_12_months": "roadmap_12_months",
    "outlook_3_years": "outlook_3_years",
    "life_alignment_scorecard": "life_alignment_scorecard",
    "strategic_correction": "strategic_correction",
    "growth_blueprint": "growth_blueprint",
    "mobile_digit_pattern": "mobile_digit_pattern",
    "life_area_impact": "life_area_impact",
    "name_vibration_optimization": "name_vibration_optimization",
    "name_mobile_combo": "name_mobile_combo",
    "numerology_architecture": "numerology_architecture",
    "planetary_influence": "planetary_influence",
    "vedic_remedy": "vedic_remedy",
    "karmic_pattern_intelligence": "karmic_pattern_intelligence",
    "pinnacle_challenge_cycle_intelligence": "pinnacle_challenge_cycle_intelligence",
    "signature_intelligence": "signature_intelligence",
    "business_name_intelligence": "business_name_intelligence",
    "environment_alignment": "environment_alignment",
    "strategic_execution_roadmap": "strategic_execution_roadmap",
    "full_identity_profile": "full_identity_profile",
    "core_numbers": "core_numbers",
    "advanced_name_numerology": "advanced_name_numerology",
    "karmic_name_analysis": "karmic_name_analysis",
    "planetary_name_support_mapping": "planetary_name_support_mapping",
    "multi_name_correction_options": "multi_name_correction_options",
    "name_optimization_scoring": "name_optimization_scoring",
    "prefix_suffix_advanced_logic": "prefix_suffix_advanced_logic",
    "mobile_numerology_advanced": "mobile_numerology_advanced",
    "mobile_digit_micro_analysis": "mobile_digit_micro_analysis",
    "mobile_energy_forecasting": "mobile_energy_forecasting",
    "name_mobile_alignment": "name_mobile_alignment",
    "dob_name_alignment": "dob_name_alignment",
    "dob_mobile_alignment": "dob_mobile_alignment",
    "full_system_alignment_score": "full_system_alignment_score",
    "strength_vs_risk_matrix": "strength_vs_risk_matrix",
    "life_area_scores": "life_area_scores",
    "mulank_deep_analysis": "mulank_deep_analysis",
    "bhagyank_destiny_roadmap": "bhagyank_destiny_roadmap",
    "lo_shu_grid_advanced": "lo_shu_grid_advanced",
    "planetary_influence_mapping": "planetary_influence_mapping",
    "current_planetary_phase": "current_planetary_phase",
    "upcoming_transit_highlights": "upcoming_transit_highlights",
    "personal_year_analysis": "personal_year_analysis",
    "monthly_cycle_analysis": "monthly_cycle_analysis",
    "critical_decision_windows": "critical_decision_windows",
    "wealth_cycle_analysis": "wealth_cycle_analysis",
    "career_growth_timeline": "career_growth_timeline",
    "relationship_timing_patterns": "relationship_timing_patterns",
    "dynamic_lucky_numbers": "dynamic_lucky_numbers",
    "situational_caution_numbers": "situational_caution_numbers",
    "neutral_number_strategy_usage": "neutral_number_strategy_usage",
    "color_strategy": "color_strategy",
    "energy_objects_recommendation": "energy_objects_recommendation",
    "advanced_remedies_engine": "advanced_remedies_engine",
    "business_brand_naming": "business_brand_naming",
    "signature_energy_analysis": "signature_energy_analysis",
    "mobile_optimization_strategy": "mobile_optimization_strategy",
    "life_strategy_recommendations": "life_strategy_recommendations",
    "priority_action_plan": "priority_action_plan",
    "risk_alerts_and_mitigation": "risk_alerts_and_mitigation",
    "premium_summary_narrative": "premium_summary_narrative",
}

SECTION_KEY_TO_HEADING_KEY.update(
    {
        "required_inputs": "required_inputs",
        "core_purpose": "core_purpose",
        "primary_focus": "primary_focus",
        "deterministic_engine": "deterministic_engine",
        "ai_generation_layer": "ai_generation_layer",
        "recommendation_logic": "recommendation_logic",
        "narration_style": "narration_style",
        "ai_narration_role": "ai_narration_role",
        "deterministic_role": "deterministic_role",
        "ai_should_not_do": "ai_should_not_do",
        "ai_should_do": "ai_should_do",
        "mobile_numerology": "mobile_numerology",
        "mobile_number_total": "mobile_number_total",
        "mobile_digit_analysis": "mobile_digit_analysis",
        "mobile_energy_description": "mobile_energy_description",
        "mulank_connection": "mulank_connection",
        "bhagyank_connection": "bhagyank_connection",
        "combo_analysis": "combo_analysis",
        "lo_shu_grid": "lo_shu_grid",
        "lucky_numbers_unlucky_numbers_neutral_numbers": "lucky_numbers_unlucky_numbers_neutral_numbers",
        "lucky_numbers": "lucky_numbers",
        "unlucky_numbers": "unlucky_numbers",
        "neutral_numbers": "neutral_numbers",
        "color_recommendation": "color_recommendation",
        "health_wealth_relationship_insight": "health_wealth_relationship_insight",
        "health_insight": "health_insight",
        "wealth_insight": "wealth_insight",
        "relationship_insight": "relationship_insight",
        "remedies": "remedies",
        "remedies_logic": "remedies_logic",
        "lucky_number_usage": "lucky_number_usage",
        "mobile_recommendation": "mobile_recommendation",
        "mobile_cover_color": "mobile_cover_color",
        "mantra_recommendation": "mantra_recommendation",
        "final_outcome": "final_outcome",
        "name_numerology": "name_numerology",
        "name_analysis": "name_analysis",
        "name_number_total": "name_number_total",
        "name_analysis_type": "name_analysis_type",
        "name_correction": "name_correction",
        "name_correction_options": "name_correction_options",
        "prefix_suffix_suggestion": "prefix_suffix_suggestion",
        "prefix_suffix_suggestions": "prefix_suffix_suggestions",
        "name_correction_basis": "name_correction_basis",
        "name_correction_logic_explanation": "name_correction_logic_explanation",
        "name_mobile_combo": "name_mobile_combo",
        "mobile_number_recommendation": "mobile_recommendation",
        "wallpaper_suggestion": "wallpaper_suggestion",
        "charging_direction": "charging_direction",
        "basic_crystal_suggestion": "bracelet_crystal_suggestion",
        "bracelet_crystal_suggestion": "bracelet_crystal_suggestion",
        "gemstone_recommendation": "gemstone_recommendation",
        "mobile_name_combo_recommendation": "mobile_name_combo_recommendation",
        "summary_and_priority_actions": "summary_and_priority_actions",
        "personal_year": "personal_year",
        "decision_timing": "decision_timing",
        "astrology_integration": "astrology_integration",
        "vedic_logic_integration": "vedic_logic_integration",
        "planetary_support_mapping": "planetary_support_mapping",
        "signature_analysis": "signature_analysis",
        "space_direction_guidance": "space_direction_guidance",
        "ongoing_guidance": "ongoing_guidance",
        "name_mobile_alignment_scored": "name_mobile_combo",
        "dob_name_alignment_deep": "dob_name_alignment",
        "dob_mobile_alignment_timing_logic": "dob_mobile_alignment",
    }
)


def _heading_key(section_key: str) -> str:
    key = str(section_key or "").strip()
    return SECTION_KEY_TO_HEADING_KEY.get(key, key)


def get_section_heading_pair(section_key: str) -> HeadingPair:
    key = _heading_key(section_key)
    heading = SECTION_HEADING_MAP.get(key)
    if heading:
        return heading
    fallback_en = key.replace("_", " ").title() if key else "Strategic Section"
    return {"en": fallback_en, "hi": "रणनीतिक अनुभाग"}


def get_bilingual_section_heading(section_key: str) -> str:
    heading = get_section_heading_pair(section_key)
    return f"{heading['en']}\n{heading['hi']}"


SECTION_TITLES: Dict[str, str] = {
    section_key: get_bilingual_section_heading(section_key)
    for section_key in SECTION_KEY_TO_HEADING_KEY
}

BASIC_BLUEPRINT_SECTIONS: List[str] = BASIC_SECTIONS
STANDARD_BLUEPRINT_SECTIONS: List[str] = STANDARD_SECTIONS
ENTERPRISE_BLUEPRINT_SECTIONS: List[str] = ENTERPRISE_SECTIONS

# Backward-compatibility aliases for legacy renderer imports.
BASIC_SECTION_KEYS: List[str] = BASIC_BLUEPRINT_SECTIONS
PREMIUM_SECTION_KEYS: List[str] = ENTERPRISE_BLUEPRINT_SECTIONS
ENTERPRISE_SECTION_KEYS: List[str] = ENTERPRISE_BLUEPRINT_SECTIONS

TIER_SECTION_KEYS: Dict[str, List[str]] = {
    "basic": BASIC_BLUEPRINT_SECTIONS,
    "standard": STANDARD_BLUEPRINT_SECTIONS,
    "pro": STANDARD_BLUEPRINT_SECTIONS,
    "premium": ENTERPRISE_BLUEPRINT_SECTIONS,
    "enterprise": ENTERPRISE_BLUEPRINT_SECTIONS,
}


def get_tier_section_blueprint(plan_name: str) -> Dict[str, object]:
    tier = (plan_name or "basic").strip().lower()
    section_keys = TIER_SECTION_KEYS.get(tier, TIER_SECTION_KEYS["basic"])

    return {
        "plan_tier": tier,
        "section_count": len(section_keys),
        "sections": [
            {
                "order": index,
                "key": key,
                "title": get_bilingual_section_heading(key),
            }
            for index, key in enumerate(section_keys, start=1)
        ],
    }


def get_all_tier_section_blueprints() -> Dict[str, Dict[str, object]]:
    return {
        tier: get_tier_section_blueprint(tier)
        for tier in ("basic", "standard", "pro", "premium", "enterprise")
    }

